name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # 选择运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 选择 Node.js 版本

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9 # 指定 pnpm 版本，可根据需要修改

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build # 构建命令，根据项目修改

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts # 构建物名称
          path: output/build # 构建物路径，根据项目修改